source "https://rubygems.org/"

gem "htmlbeautifier"
gem "json", ">= 2.20"
gem "mysql2", ">= 0.5.7"
gem "sinatra", ">= 4.2.1"
gem "sinatra-contrib" # fornece Reloader
gem "tailwindcss-ruby", ">= 4.3.1"
gem 'bcrypt', '>= 3.1.22'
gem 'dotenv'
gem "puma"
gem "rackup"